/**
 * notification.model.ts — In-App Notification Schema
 *
 * Stores in-app notifications generated by the reminder scheduler.
 */
import mongoose, { Schema, Document, Model } from 'mongoose';

export interface INotification extends Document {
  userId:      mongoose.Types.ObjectId;
  documentId?: mongoose.Types.ObjectId;
  title:       string;
  body:        string;
  eventType?:  string;
  docName?:    string;
  subtitle?:   string;
  read:        boolean;
  createdAt:   Date;
  updatedAt:   Date;
}

const NotificationSchema = new Schema<INotification>(
  {
    userId:     { type: mongoose.Schema.Types.ObjectId, ref: 'User',     required: true, index: true },
    documentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Document', required: false },
    title:      { type: String, required: true },
    body:       { type: String, required: true },
    eventType:  { type: String, default: 'reminder' },
    docName:    { type: String },
    subtitle:   { type: String },
    read:       { type: Boolean, default: false, index: true },
  },
  { timestamps: true, versionKey: false },
);

// Compound index: per-user, unread first
NotificationSchema.index({ userId: 1, read: 1, createdAt: -1 });

export const NotificationModel: Model<INotification> =
  mongoose.model<INotification>('Notification', NotificationSchema);
